spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house_rental?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location:
  - classpath:mapper/*.xml

logging:
  level:
    com.kaituo.communitypolicing : debug

